apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- config.yaml
namespace: hello-app-blue
images:
- name: github-actions-example
  newName: dbatruh/github-actions-example
  newTag: 3164a7aebfdc946e466f9e90321a243cdd74ddd6
