name: CI/CD Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Test with pytest
      run: |
        pytest

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    
    - uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./app 
        file: ./app/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/github-actions-example:build-${{ github.run_number }}
        platforms: linux/amd64,linux/arm64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

  deploy: 
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    
    env:
      PROJECT_ID: ${{ secrets.GKE_PROJECT }}
      GKE_CLUSTER: autopilot-cluster-1
      GKE_REGION: us-central1

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Install gke-gcloud-auth-plugin
      uses: "google-github-actions/setup-gcloud@v2"
      with:
        install_components: "gke-gcloud-auth-plugin"
    
    - name: Authenticate to GKE cluster
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: '${{ secrets.GKE_CLUSTER }}'
        location: '${{ secrets.GKE_REGION }}'

    - name: Create namespaces
      run: |
        namespacePresentBlue=`kubectl get ns | grep hello-blue | wc -l`
        namespacePresentGreen=`kubectl get ns | grep hello-green | wc -l`
        if [ $namespacePresentBlue -eq 0 ] && [ $namespacePresentGreen -eq 0 ]; then
          echo "Both blue and green namespaces are absent. Exiting."
          exit 1
        fi
        if [ $namespacePresentBlue -eq 0 ]; then
          kubectl create ns hello-blue
          echo "Created hello-blue namespace"
        fi
        if [ $namespacePresentGreen -eq 0 ]; then
          kubectl create ns hello-green
          echo "Created hello-green namespace"
        fi
    - name: Apply Config Map
      run: |
        kubectl apply -f k8s/hello-blue-config.yaml -n hello-blue
    - name: Deploy blue version (if not deployed)
      run: |
        kubectl apply -f k8s/hello-blue.yaml -n hello-blue
        kubectl set image deployment/hello-deployment-blue hello-container=${{ secrets.DOCKER_USERNAME }}/github-actions-example:build-${{ github.run_number }} -n hello-blue
      
    - name: Test blue deployment
      run: |
        BLUE_URL=$(kubectl get svc hello-service -n hello-blue -o=jsonpath='{.spec.clusterIP}:{.spec.ports[0].port}')
        echo "Blue deployment URL: $BLUE_URL"
        curl $BLUE_URL || exit 1  # If curl fails, exit the pipeline
        kubectl get pods -n hello-blue

    - name: Apply Config Map
      run: |
        kubectl apply -f k8s/hello-green-config.yaml -n hello-green
    - name: Deploy green version (new version)
      run: |
        kubectl apply -f k8s/hello-green.yaml -n hello-green
        kubectl set image deployment/hello-deployment-green hello-container=${{ secrets.DOCKER_USERNAME }}/github-actions-example:build-${{ github.run_number }} -n hello-green

    - name: Test green deployment
      run: |
        GREEN_URL=$(kubectl get svc hello-service -n hello-green -o=jsonpath='{.spec.clusterIP}:{.spec.ports[0].port}')
        echo "Green deployment URL: $GREEN_URL"
        curl $GREEN_URL || exit 1  # If curl fails, exit the pipeline
        kubectl get pods -n hello-green

    - name: Switch traffic to green version
      run: |
        kubectl patch service hello-service -p '{"spec":{"selector":{"app":"hello-app","environment":"green"}}}'
        echo "Traffic is now routed to green version"
 
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add k8s/*.yaml
        git commit -m "Update resource files with new Docker tag 'build-${{ github.run_number }}'"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} 
